### ISSUE TITLE
Webpack error while registering by babel

### ISSUE THREAD

**Issue by esneko** [websecurify/babel-plugin-import-css-to-jss#1]
Weird issue with webpack when plugin is loaded with babel:

``` js
var express = require('express')
var webpack = require('webpack')

var babelConfig = {
  plugins: ['transform-runtime', 'import-css-to-jss'],
  presets: ['react', 'es2015', 'stage-0']
}
var webpackConfig = {
  entry: [
    './app'
  ],
  module: {
    loaders: [{
      test: /\.jsx?$/,
      loader: 'babel-loader'
    }]
  }
}
require('babel-core/register')(babelConfig)
var compiler = webpack(webpackConfig)

var app = new express()
app.use(require('webpack-dev-middleware')(compiler))
app.use(require('webpack-hot-middleware')(compiler))
```

```
node_modules/webpack/lib/webpack.js:27
        throw new Error("Invalid argument: options");
        ^
Error: Invalid argument: options
    at webpack (/node_modules/webpack/lib/webpack.js:27:9)
    at Object.<anonymous> (server.js:10:18)
    at Module._compile (module.js:397:26)
    at loader (/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by esneko** [comment]
Sorry, my fault.
Should be `loader: 'babel'` instead of `loader: 'babel-loader'`.
